name: PR Build
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: takuyaohashi/setup-flutter@v1
      with:
        flutter-version: 'latest'
        channel: 'beta'
    - name: Flutter Analyze
      run: flutter analyze .
    - name: Enable Web Build
      run: flutter config --enable-web
    - name: Build for Web
      run: flutter build web --pub --csp
